# Generated by Django 6.0.6 on 2026-06-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('thumbnails', models.ImageField(blank=True, upload_to='images/thumbnails/')),
                ('project_url', models.URLField()),
                ('github_url', models.URLField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
