# Generated by Django 6.0.6 on 2026-06-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnails',
            field=models.ImageField(blank=True, upload_to='../images/thumbnails/'),
        ),
    ]
