# Generated by Django 6.0.6 on 2026-06-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnails',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
