# Generated by Django 6.0.6 on 2026-06-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='member/')),
                ('awards', models.JSONField(default=list)),
                ('roles', models.JSONField(default=list)),
                ('description', models.TextField()),
            ],
        ),
    ]
