# Generated by Django 6.0.6 on 2026-06-20 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(blank=True, max_length=150, null=True)),
                ('testimonial_image', models.ImageField(upload_to='../images/testimonials/')),
                ('remarks', models.TextField()),
                ('rating', models.IntegerField(help_text='Rate from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
