# Generated by Django 6.0.6 on 2026-06-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
